### ISSUE TITLE
Unable to specify Sheet Name for processFile

### ISSUE THREAD

**Issue by binarymax** [stevetarver/excel-as-json#11]
In some spreadsheets with multiple sheets, it is desirable to specify which sheet to convert (currently it is only possible to convert 'Sheet 1', and will throw an exception if that sheet cannot be converted).

The solution would be to accept another (optional) parameter for the processFile method, but that would result in a breaking change in the API.

The change would be to accept the sheet name and alter the call on line 148 of excel-as-json.coffee from this:

```coffeescript
excel src, (err, data) ->
```

to  this:

```coffeescript
excel src, sheet, (err, data) ->
```

I am happy to make the change, but if you have a preference on how to accept the sheet name in processFile please let me know!

(PS - thanks for this module, it's been very useful and has saved me lots of time)

**Comment by stevetarver** [comment]
binarymax - first: thanks for your research and courteous note - that is rare and appreciated - glad this little file could simplify your life.

I don't believe the "excel" package I am using can parse other than the first sheet in an xlsx file - it could not when I wrote this package - implying selecting a more robust excel package that has the same parsing/empty cell behavior.

I am completely swamped at work and will not be able to look into this any time soon - like months :(

The main entry point is processFile, so the sheet index or name would have to be passed in there. Seems like the sheet id/name should go next to the src file name so

```
// now
processFile = (src, dst, isColOriented=false, callback=undefined) ->

// proposed
processFile = (src, sheet, dst, isColOriented=false, callback=undefined) ->
```

Since this is a breaking signature change, I would need to bump the version to 2.x.x and I would also want to change isColOriented to an options object to allow more feature flags like how to handle empty cells - make them empty strings or omit them from the json.

If you take the time to fix this, I will make the time to review it. Standard process -> fork it, work in a meaningful branch name, submit a PR.

**Comment by binarymax** [comment]
My pleasure.  I had already made a fork but realized I should probably check with you before making the change and sending a PR.

The ```excel``` module version as specified in your ```package.json``` does indeed support specification of the sheet name, optionally as the 2nd argument, which is how I specified in the note above.

I'll be able to send a PR sometime in the next day or so.

Thanks!

**Comment by stevetarver** [comment]
very cool - appreciate it

**Comment by binarymax** [comment]
Thanks for the merge!  Closing this issue :)
