### ISSUE TITLE
Can i use it for uploading a excel sheet to firestore using angular 5 for huge amount of data in the excel sheet

### ISSUE THREAD

**Issue by puhu1** [stevetarver/excel-as-json#39]

**Comment by stevetarver** [comment]
@puhu1: I have done absolutely no performance testing on this package - it was originally designed as a Grunt task to create static data on project build. My guess is that performance will be defined by what the libxmljs and excel packages I depend on can do - my code is light "decoration" on top of those packages.

Some implementation questions occur to me:
- do you want your users to sit through parsing and upload?
- will your user's computers and browser have enough RAM to pull the spreadsheet into memory?
- if the user processes a couple of spreadsheets, will your app eat all their RAM?
- what happens if a connection is interrupted during upload - will that be a good user experience?

There are already good tools for reliable file upload. Have you considered uploading the xlsx file and creating a server side task that does the import? That way, the parse and upload happens on a server you control, and you will likely have good bandwidth. You also won't care about speed - it will be an offload task and not really impacting user experience.
