### ISSUE TITLE
Coffeescript docs

### ISSUE THREAD

**Issue by oojacoboo** [stevetarver/excel-as-json#43]
Why are the doc examples in Coffeescript?  Is this your syntactic dogma?

**Comment by stevetarver** [comment]
I guess this issue is indirectly asking about history... When I wrote this 3.5 years ago, I wanted to see what living with coffeescript was like. Wrote the front end of a dashboard style web site in it and this was an offshoot used to generate static pricing models ETLd into excel. Also made a Grunt (remember Grunt ;) - before Gulp, before webpack) plugin for it so the static data was generated during front end build.

Overall, I would consider the experiment a success. I really like the "less busy" languages like coffeescript, ruby, and python. The code is simple, clean, and there is much less of it - nice to maintain. Not many of the front end developers liked it, so they ended up rewriting the site in javascript (meaning: switched over to the transpiled version).

So, doc is in coffeescript cause code is in coffeescript and it was easy to test and prove the examples.
